dist: focal

language: go

env:
  - GO111MODULE=on

go:
  - 1.16.x

git:
  depth: 1
  
script:
  - go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
